### ISSUE TITLE
Ausführlichere Beschreibung

### ISSUE THREAD

**Issue by d-w216** [MarinkoBa/CovidImpfzentrenChisinau#1]
Die Modelle für QGIS funktionieren nicht, wenn sie mit Drag and Drop reinzieht. Dies könnte umgangen werden, wenn man genauer beschreibt wie man die Modelle in QGIS laden soll.

**Comment by d-w216** [comment]
GitHub Respository: "QGISModelPart1", Batch-Script: "calculate_distances_grassgis" und "QGISModelPart2"

Hierbei muss noch der Datentyp spezifiziert werden (Shapefile) da dieses nicht automatisch eingestellt ist.

**Comment by d-w216** [comment]
- genauer spezifizieren, dass die Daten aus der Heibox und die GitHub Sachen in ein Ordner sollen ( ohne den Ordner Daten)

-"GRASS GIS öffnen und mit "cd" zum richtigen Ordner (in dem alle heruntegeladenen Daten sind) navigieren"

- Im Batch-Script könnte man noch dafür sorgen, dass bereits exestierende Files überschrieben werden.

**Comment by MarinkoBa** [comment]
Zu QGIS Modell laden:
![Model_Laden_QGIS](https://user-images.githubusercontent.com/64740488/107633128-d1aae000-6c67-11eb-9be5-d1b7b61df791.PNG)

**Comment by MarinkoBa** [comment]
Vielen Dank für die Kommentare. Ist eine gute Idee die vorhandenen Dateien automatisch im Batch-Script File zu überschreiben.
