### ISSUE TITLE
Nicht ausführbar: geoTOPSIS" und "geoWeightedSum"

### ISSUE THREAD

**Issue by d-w216** [MarinkoBa/CovidImpfzentrenChisinau#2]
-"durchprobieren verschiedene Werte für die Gewichte bei den Faktoren der Algorithmen (nur normalisierte "norm" Spalten als Faktoren nutzen, alle anderen Spalten mit Rechtsklick aus der Tabelle entfernen)"

Ohne weitere Informationen ist der Algorithmus nicht ausführbar.

**Comment by MarinkoBa** [comment]
Beispielhafte Nutzung der vectorMCDA Algorithmen:

![GeoTopsysAusfuehrung](https://user-images.githubusercontent.com/64740488/107634350-ad500300-6c69-11eb-9f36-6fcaa81b3f7b.PNG)


Nach der Auswahl der Gewichte muss man auf "Apply" klicken und anschließend auf die Analysis links unten um zu einem neuen Fenster zu gelangen. Danach klickt man auf Load Maps:

![LoadMaps](https://user-images.githubusercontent.com/64740488/107634580-0ae44f80-6c6a-11eb-8910-cea0da961a8b.PNG)
